### ISSUE TITLE
Galactic Navigation Parameters

### ISSUE THREAD

**Issue by bekirbostanci** [neobotix/neo_simulation2#48]
With the default parameters on galactic robot is not navigate on the map. However if you change the parameters with the foxy (controller server parameters) it can navigate.  

// foxy parameters
```
controller_server:
  ros__parameters:
    # controller server parameters (see Controller Server for more info)
    use_sim_time: True
    controller_frequency: 50.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True
    # RegulatedPurePursuitController Parameters
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 1.2
      max_linear_accel: 0.8
      max_linear_decel: 0.8
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3 #0.3
      max_lookahead_dist: 0.9 #0.9
      lookahead_time: 1.5 #1.5
      rotate_to_heading_angular_vel: 0.9
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.01
      use_approach_linear_velocity_scaling: true
      max_allowed_time_to_collision: 1.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius:  0.9
      regulated_linear_scaling_min_speed: 0.25
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 10.0
      allow_reversing: false
```

//galactic parameters
```controller_server:
  ros__parameters:
    # controller server parameters (see Controller Server for more info)
    use_sim_time: True
    controller_frequency: 50.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True
    # RegulatedPurePursuitController Parameters
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      max_linear_accel: 0.2
      max_linear_decel: 0.2
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3 #0.3
      max_lookahead_dist: 0.9 #0.9
      lookahead_time: 1.5 #1.5
      rotate_to_heading_angular_vel: 0.6
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.01
      use_approach_linear_velocity_scaling: true
      max_allowed_time_to_collision: 1.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius:  0.9
      regulated_linear_scaling_min_speed: 0.25
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 0.6
      allow_reversing: false```
